#development:
#  adapter: mysql2
#  database: roof
#  username: root
#  password: niket
#  pool: 5
#  host: localhost
development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: niket
test:
  adapter: mysql2
  database: roof
  username: root
  password: niket
  pool: 5
  host: localhost

  production:
    adapter: mysql2
    encoding: utf8
    database: <%= ENV['RDS_DB_NAME'] %>
    username: <%= ENV['RDS_USERNAME'] %>
    password: <%= ENV['RDS_PASSWORD'] %>
    host: <%= ENV['RDS_HOSTNAME'] %>
    port: <%= ENV['RDS_PORT'] %>