development:
  adapter: mysql2
  database: roof
  username: root
  password: niket
  pool: 5
  host: localhost
test:
  adapter: mysql2
  database: roof
  username: root
  password: niket
  pool: 5
  host: localhost
production:
  adapter: mysql2
  database: roof
  username: root
  password: niket
  pool: 5
  host: localhost